import './globals.css'
import { Inter, Lato } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] }) 

const lato = Lato({ subsets: ['latin'], weight:['100', '300', '400', '700', '900']})

export const metadata = {
  title: 'PaperID',
  description: 'PaperID Test Case generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  )
}
